name: "Tester"

on:
  pull_request:

  push:
    branches: [ "*" ]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test84:
    name: "Tester"
    uses: contributte/.github/.github/workflows/phpunit.yml@v1
    with:
      php: "8.4"
      make: "init tests"
